# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.__version__)
print(np.show_config())

2.3.3
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.3",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      

/Users/smithn5/ironhack/labs/.venv/lib/python3.11/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
### [your code here]
a = np.random.random((2, 3, 5))
print(a.shape)

(2, 3, 5)



### 4. Print a.


In [11]:
### [your code here]
print(a)

[[[0.01386579 0.16612561 0.86134338 0.1135286  0.46299382]
  [0.44353185 0.32269004 0.71574284 0.98556389 0.71381762]
  [0.37400886 0.36333966 0.39456945 0.8090469  0.34433373]]

 [[0.84208961 0.78300789 0.41282646 0.10042595 0.40621888]
  [0.31242008 0.35319104 0.90670909 0.82641371 0.77170052]
  [0.92091822 0.76121196 0.59318995 0.47497397 0.97248945]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [9]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
### [your code here]
a.size == b.size

True


### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
a + b
# different shapes, but same size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [22]:
### [your code here]
#Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array)
c = b.transpose(1, 2, 0)




### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [24]:
### [your code here]
d =c + a


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)
# added 1 to each element in a


[[[0.01386579 0.16612561 0.86134338 0.1135286  0.46299382]
  [0.44353185 0.32269004 0.71574284 0.98556389 0.71381762]
  [0.37400886 0.36333966 0.39456945 0.8090469  0.34433373]]

 [[0.84208961 0.78300789 0.41282646 0.10042595 0.40621888]
  [0.31242008 0.35319104 0.90670909 0.82641371 0.77170052]
  [0.92091822 0.76121196 0.59318995 0.47497397 0.97248945]]]
[[[1.01386579 1.16612561 1.86134338 1.1135286  1.46299382]
  [1.44353185 1.32269004 1.71574284 1.98556389 1.71381762]
  [1.37400886 1.36333966 1.39456945 1.8090469  1.34433373]]

 [[1.84208961 1.78300789 1.41282646 1.10042595 1.40621888]
  [1.31242008 1.35319104 1.90670909 1.82641371 1.77170052]
  [1.92091822 1.76121196 1.59318995 1.47497397 1.97248945]]]



### 12. Multiply a and c. Assign the result to e.


In [27]:
### [your code here]
e = a * c




### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
a == e
# multiplying by 1 does not change the array

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [44]:
### [your code here]
# flatten d
d_flat = d.flatten()
d_max = np.max(d_flat)
d_min = np.min(d_flat)
d_mean = np.mean(d_flat)
print(d_max, d_min, d_mean)


1.9855638911438103 1.0138657923919459 1.5507429616658586



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [41]:
### [your code here]
# create an empty array of shape (2, 3, 5)
f = np.empty(d.shape)
f[:] = np.nan
print(f)

[[[nan nan nan nan nan]
  [nan nan nan nan nan]
  [nan nan nan nan nan]]

 [[nan nan nan nan nan]
  [nan nan nan nan nan]
  [nan nan nan nan nan]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [45]:
### [your code here]
f[np.where(d == d_min)] = 0
f[np.where((d > d_min) & (d < d_mean))] = 25
f[np.where((d > d_mean) & (d < d_max))] = 75
f[np.where(d == d_mean)] = 50
f[np.where(d == d_max)] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [46]:
### [your code here]
print(d)
print(f)

[[[1.01386579 1.16612561 1.86134338 1.1135286  1.46299382]
  [1.44353185 1.32269004 1.71574284 1.98556389 1.71381762]
  [1.37400886 1.36333966 1.39456945 1.8090469  1.34433373]]

 [[1.84208961 1.78300789 1.41282646 1.10042595 1.40621888]
  [1.31242008 1.35319104 1.90670909 1.82641371 1.77170052]
  [1.92091822 1.76121196 1.59318995 1.47497397 1.97248945]]]
[[[  0.  25.  75.  25.  25.]
  [ 25.  25.  75. 100.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  75.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [49]:
### [your code here]
f = f.astype(str)
f[np.where(d == d_min)] = 'A'
f[np.where((d > d_min) & (d < d_mean))] = 'B'
f[np.where((d > d_mean) & (d < d_max))] = 'C'
f[np.where(d == d_mean)] = 'D'
f[np.where(d == d_max)] = 'E'

In [50]:
print(f)    

[[['A' 'B' 'C' 'B' 'B']
  ['B' 'B' 'C' 'E' 'C']
  ['B' 'B' 'B' 'C' 'B']]

 [['C' 'C' 'B' 'B' 'B']
  ['B' 'B' 'C' 'C' 'C']
  ['C' 'C' 'C' 'B' 'C']]]
